baseURL = 'https://willbutton.com'
languageCode = 'en-us'
title = 'Will Button'
theme = 'PaperMod'

[params]
  description = "30-year tech veteran learning DeFi in public. Making complex protocols accessible while maintaining peak performance across life's four spinning plates."
  author = "Will Button"

[taxonomies]
  category = "categories"
  tag = "tags"

[menu]
  [[menu.main]]
    name = "DeFi Journey"
    url = "/categories/defi/"
    weight = 10
  [[menu.main]]
    name = "Four Plates"
    url = "/categories/performance/"
    weight = 20
  [[menu.main]]
    name = "Tech Career"
    url = "/categories/career/"
    weight = 30
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 40

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
